spring:
    kafka:
        bootstrap-servers: ${BOOTSTRAP_SERVERS}
        consumer:
            group-id: ${GROUP_ID}
            max-partition-fetch-bytes: ${KAFKA_MAX_PARTITION_FETCH_BYTES}
        topics:
            producer-topic: ${USER_EVENT_TOPIC}
            consumer-topic: ${RESPONSE_EVENT_TOPIC}
    datasource:
        platform: postgres
        url: ${DB_CONNECTION}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        initialization-mode: always
        continue-on-error: false
    flyway:
        locations: classpath:db/migration
        enabled: true
        default-schema: kesa_auth
        schemas: kesa_auth
    jpa:
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.PostgreSQLDialect
    mvc:
        throw-exception-if-no-handler-found: true
    # Warning: configure mail testing set up below when running locally with docker do not use configuration in docker compose
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        kesa:
            subject: KESA Demo Request
            sender: ${EMAIL_SENDER}
            sender_title: KESA Demo
            recipients: ${EMAIL_RECIPIENTS}