bootstrap.servers=kafka:9092
application.id=kq-sink-application
max.partition.fetch.bytes=4500000
source_topic_regex=event-log
db_connection=jdbc:postgresql://postgres-db:5432/kqdb
db_user=postgres
db_password=password