/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kafkaquest.kq.aggregate;

import com.kafkaquest.kq.aggregate.config.KQAggregateAppConfig;
import com.kafkaquest.kq.aggregate.services.EventProcessor;
import com.kafkaquest.kq.aggregate.services.JdbiConnection;
import com.kafkaquest.kq.common.util.models.events.AggregateEvent;
import com.kafkaquest.kq.common.util.models.kafkakeys.AggregateKey;
import com.kafkaquest.kq.common.util.models.kafkakeys.ApiKey;
import com.kafkaquest.kq.common.util.config.Environment;
import com.kafkaquest.kq.common.util.serializer.AggregateEventDeserializer;
import com.kafkaquest.kq.common.util.serializer.AggregateEventSerializer;
import com.kafkaquest.kq.common.util.serializer.AggregateKeyDeserializer;
import com.kafkaquest.kq.common.util.serializer.AggregateKeySerializer;
import com.kafkaquest.kq.common.util.serializer.ApiKeyDeserializer;
import com.kafkaquest.kq.common.util.serializer.ApiKeySerializer;
import org.apache.kafka.common.serialization.Serde;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.Topology;
import org.apache.kafka.streams.errors.StreamsUncaughtExceptionHandler;
import org.apache.kafka.streams.kstream.Consumed;
import org.apache.kafka.streams.kstream.Produced;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Arrays;
import java.util.regex.Pattern;

public class Application {

    private static final Logger LOGGER = LoggerFactory.getLogger(Application.class);

    private static KQAggregateAppConfig appConfig;

    public static void configureEnvironment(String... varArgs) {
        final var env = Arrays.asList(varArgs).contains(Environment.DOCKER.getValue())
                ? Environment.DOCKER
                : Environment.LOCAL;

        appConfig = new KQAggregateAppConfig(env);
        JdbiConnection.initialize(appConfig);
    }

    public static Topology getTopology() {
        Serde<ApiKey> apiKeySerde = Serdes.serdeFrom(
                new ApiKeySerializer(),
                new ApiKeyDeserializer()
        );

        Serde<AggregateKey> aggregateKeySerde = Serdes.serdeFrom(
                new AggregateKeySerializer(),
                new AggregateKeyDeserializer()
        );

        Serde<AggregateEvent> aggregateEventSerde = Serdes.serdeFrom(
                new AggregateEventSerializer(),
                new AggregateEventDeserializer()
        );

        StreamsBuilder builder = new StreamsBuilder();

        builder.stream(
            Pattern.compile(appConfig.getSourceTopicRegex()),
            Consumed.with(apiKeySerde, new Serdes.ByteArraySerde())
        )
        .flatMap(EventProcessor::process)
        .to(
            appConfig.getSinkTopic(),
            Produced.with(aggregateKeySerde, aggregateEventSerde)
        );

        return builder.build();
    }

    public static void main(String[] args) {
        configureEnvironment(args);

        Topology topology = getTopology();

        KafkaStreams kafkaStreams = new KafkaStreams(topology, appConfig.getKafkaProperties());
        kafkaStreams.setUncaughtExceptionHandler((e) -> {
            LOGGER.error(e.getMessage(), e);
            return StreamsUncaughtExceptionHandler.StreamThreadExceptionResponse.REPLACE_THREAD;
        });

        kafkaStreams.start();

        Runtime.getRuntime().addShutdownHook(new Thread(kafkaStreams::close));
    }
}
